name: Auto Release

on:
  push:
    branches: [main, 'release/*']
  pull_request:
    types: [ready_for_review]
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      has_changes: ${{ steps.release.outputs.has_changes }}
    steps:
      - id: release
        uses: cad0p/semver-calver-release/release@main
        with:
          skip_release: ${{ github.event_name == 'pull_request' || github.ref != 'refs/heads/main' }}
          ref: ${{ github.head_ref || github.ref }}
