name: Validate Release PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: cad0p/semver-calver-release/validate-release-pr@main
